FORMAT: 1A
HOST: https://cloud.notifica.re/api

# Notificare CLOUD API
This is an official Notificare API that enables access to certain features of our platform specially designed for your mobile and web front-end apps. Its sole purpose is to provide access to strategic endpoints via a front-end application.
The API endpoints below are all authenticated with `applicationKey` and `applicationSecret`, if you do not have these yet, you should grab them from your app in Notificare Dashboard under the section Settings > App Keys.
Use Basic HTTP Authentication where `applicationKey` should be your username and `applicationSecret` your password. If you intend to use this API from your mobile application, you can access all the endpoints provided here through the Cloud API method available in our SDKs.

This API requires activations before you can use it. To activate or get more information about this API, please [contact us](http://notifica.re/contact).

## Docs have moved!

REST API documentation has moved to a [new location](https://api-docs.notifica.re/cloud/), please update your bookmarks.
