FORMAT: 1A
HOST: https://cloud.notifica.re/api

# Notificare CLOUD API
This is an official Notificare API that enables access to certain functionality of our platform to mobile and web apps. Its sole purpose is to provide apps access to REST API endpoints without having to build your own back-end connection to our standard REST API.
The API calls below are all authenticated with `applicationKey` and `applicationSecret`, if you do not have these yet, you should grab them from your app in Notificare Dashboard under the section Settings > App Keys.
Use Basic HTTP Authentication where `applicationKey` should be your username and `applicationSecret` your password. If you intend to use this API from your mobile application, you can access all the endpoints provided here through the Cloud API method available in our SDKs.

For more information about this API, please [contact us](http://notifica.re/contact).


## Application [/application/info]

### Retrieve information about the application [GET]

+ Response 200 (application/json)

    {
        "application": {
            "_id": "xxx",
            "name": "Notificare App",
            "category": "Business",
            "appStoreId": null,
            "androidPackageName": null,
            "services": {
                "richPush": true,
                "locationServices": true,
                "apns": true,
                "gcm": true,
                "websockets": true,
                "triggers": true,
                "passbook": true,
                "inAppPurchase": true,
                "oauth2": true,
                "screens": true,
                "reports": true,
                "appsOnDemand": true,
                "liveApi": true,
                "automation": true,
                "websitePush": true,
                "inbox": true,
                "storage": true
            },
            "inboxConfig": {
                "useInbox": true,
                "autoBadge": true
            },
            "userDataFields": [],
            "actionCategories": [],
            "regionConfig": {
                "proximityUUID": null
            },
            "websitePushConfig": {
                "icon": "/website-push/xxx/xxx",
                "allowedDomains": ["http://mydomain.com"],
                "urlFormatString": "http://mydomain.com/?notification=%@",
                "info": {
                    "subject": {
                        "C": "US",
                        "O": "Notificare B.V.",
                        "OU": "xxxx",
                        "CN": "Website Push ID: web.com.mydomain",
                        "UID": "web.com.mydomain"
                    }
                }
            }
        }
    }


## Asset Groups [/assets/forgroup/{name}]

### Retrieve a group of assets by name [GET]

+ Response 200 (application/json)

        {
            "assets": [{
                "title": "My Asset Group",
                "key": "xxx/xxx",
                "description": "",
                "_id": "xxx",
                "button": {
                    "label": null,
                    "action": null
                },
                "metaData": {
                    "contentLength": 501,
                    "contentType": "application/json",
                    "originalFileName": "myjsonfile.json"
                }
            }]
        }